#Sources
:sources:
  Company:
    :poll_interval: 30

:development:
  :licensefile: settings/license.key
  :redis: 192.168.2.22:6379
  :syncserver: http://192.168.2.22:9292/api/application/
  :push_server: http://someappname@192.168.2.22:8675/
  :api_token: my-rhoconnect-token
:test:
  :licensefile: settings/license.key
  :redis: 192.168.2.22:6379
  :syncserver: http://192.168.2.22:9292/api/application/
  :push_server: http://someappname@192.168.2.22:8675/
  :api_token: my-rhoconnect-token
:production:
  :licensefile: settings/license.key
  :redis: 192.168.2.22:6379
  :syncserver: http://192.168.2.22:9292/api/application/
  :push_server: http://someappname@192.168.2.22:8675/
